language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --compilers js:babel-register --report lcovonly -- -R spec test/**/*.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
